### ISSUE TITLE
Should I receive one OnClose for every connection created and closed?

### ISSUE THREAD

**Issue by mehrvarz** [lesismal/nbio#71]
Hi. I am using nbio hard and it is performing very well. But here might be a small issue: I depend on OnClose for properly reverting things to the initial state. For example, I create a bunch of connections (say, 20000) using a synthetic test tool. And then I close all of these connections at once. In such case I seem to often end up with a small percentage of connections not receiving an OnClose event. The problem seems to occur especially when I just kill the client tool, ending all connections without properly closing them down. The vast majority of the connections does still receive it's OnClose event on the server side. But some (say, 279 out of 20000) do not. This could very well be an oddity in my app. But I can't find the issue. NOTE: I have print statements in OnClose. As a result it often takes some significant amount of time to gp through all OnClose events. Could this be causing the issue?
Same context: What do the different OnClose error messages mean: 1. no error, 2. "EOF", 3. "broken pipe" and 4. "connection timed out". What can I derive from these error messages? Do any of them demand special (different) action on my part? Currently I am NOT closing any connection for which I receive an OnClose event (assuming they are closed already). Is this the correct handling of it?

**Comment by lesismal** [comment]
> 1. no error
>
If your server-side calls conn.Close(), you will get "nil error".

> 2. "EOF"
>
If the client-side calls conn.Close() and your server-side read it, you will get "EOF".

> 3. "broken pipe"
>
When a conn has been closed, and the server-side calls conn.Write(), you will get about this error. nbio support concurrent reading/writing, we do not promise the read and write in order.

> 4. "connection timed out"
>
For example, http and websocket, we usually set a timeout for reading a whole request/frame message, if there was not enough data coming, nbio/nbhttp will close the conn with "timeout error"


> For example, I create a bunch of connections (say, 20000) using a synthetic test tool. And then I close all of these connections at once. In such case I seem to often end up with a small percentage of connections not receiving an OnClose event. The problem seems to occur especially when I just kill the client tool, ending all connections without properly closing them down. The vast majority of the connections does still receive it's OnClose event on the server side. But some (say, 279 out of 20000) do not. This could very well be an oddity in my app. But I can't find the issue.
>

Please provide your example code and I will try to reproduce it and find out the reason.

**Comment by mehrvarz** [comment]
> > 1. no error
> 
> If your server-side calls conn.Close(), you will get "nil error".
> 
> > 1. "EOF"
> 
> If the client-side calls conn.Close() and your server-side read it, you will get "EOF".

Didn't know that.

I have noticed something interesting. My app supports two types of clients: hosting clients and joining clients. When a joined client leaves a session, the hosting client may continue to stay online. But when a hosting client exits first, the server needs to kick out the joined client. This is one of the rare cases where my server needs to close a healthy client connection. And this is what I am having problems with.

Things happen in this order: server receives OnClose for the leaving hosting client (err="broken pipe"). The server sees that there is a joined client, which must be closed. So it calls: wsConn.WriteMessage(websocket.CloseMessage, nil) (framed by a mutex), followed by: wsConn.Close(). Before wsConn.Close() returns, an OnClose event is received (this one with no error!). Then wsConn.Close() returns. Everything is looking fine. However, the closed client does not exit. It does not react at all. It simply does nothing.

Things look much better if all the joined clients exit before the hosting client (so that no explicit Close() is necessary). In this case will my server receive all the required OnClose events and it can bring everything back to the initial state.

But when all hosting clients exit first, causing the joined clients to be force closed, the server will NOT receive all the expected OnClose events, wrongly leaving some xxx out of xxxxx session "unclosed". And the joined clients will simply stay "connected" from their own perspective. Interesting: when I now kill the server, all the zombi clients will immediately receive a "connection reset by peer" message. Why can my server not properly force close (kick out) connected clients? (Using Gorilla for the clients. Also tried fasthttp/websocket but no change.)

**Comment by lesismal** [comment]
> > > 1. no error
> > 
> > 
> > If your server-side calls conn.Close(), you will get "nil error".
> > > 1. "EOF"
> > 
> > 
> > If the client-side calls conn.Close() and your server-side read it, you will get "EOF".
> 
> Didn't know that.
> 
> I have noticed something interesting. My app supports two types of clients: hosting clients and joining clients. When a joined client leaves a session, the hosting client may continue to stay online. But when a hosting client exits first, the server needs to kick out the joined client. This is one of the rare cases where my server needs to close a healthy client connection. And this is what I am having problems with.
> 
> Things happen in this order: server receives OnClose for the leaving hosting client (err="broken pipe"). The server sees that there is a joined client, which must be closed. So it calls: wsConn.WriteMessage(websocket.CloseMessage, nil) (framed by a mutex), followed by: wsConn.Close(). Before wsConn.Close() returns, an OnClose event is received (this one with no error!). Then wsConn.Close() returns. Everything is looking fine. However, the closed client does not exit. It does not react at all. It simply does nothing.
> 
> Things look much better if all the joined clients exit before the hosting client (so that no explicit Close() is necessary). In this case will my server receive all the required OnClose events and it can bring everything back to the initial state.
> 
> But when all hosting clients exit first, causing the joined clients to be force closed, the server will NOT receive all the expected OnClose events, wrongly leaving some xxx out of xxxxx session "unclosed". And the joined clients will simply stay "connected" from their own perspective. Interesting: when I now kill the server, all the zombi clients will immediately receive a "connection reset by peer" message. Why can my server not properly force close (kick out) connected clients? (Using Gorilla for the clients. Also tried fasthttp/websocket but no change.)

So you mean it occurred when the server-side called conn.Close()?

Full example code would be helpful.

**Comment by lesismal** [comment]
I tried with this example:

### server
```golang
package main

import (
	"fmt"
	"net/http"
	"runtime"
	"sync/atomic"
	"time"

	"github.com/lesismal/nbio"
	"github.com/lesismal/nbio/mempool"
	"github.com/lesismal/nbio/nbhttp"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

var (
	qps   uint64 = 0
	total uint64 = 0

	svr *nbhttp.Server
)

func onWebsocket(w http.ResponseWriter, r *http.Request) {
	upgrader := websocket.NewUpgrader()
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		panic(err)
	}
	wsConn := conn.(*websocket.Conn)
	wsConn.SetReadDeadline(time.Now().Add(time.Second * 5))
	wsConn.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
		wsConn.SetReadDeadline(time.Now().Add(time.Second * 5))
		c.WriteMessage(messageType, data)
		atomic.AddUint64(&qps, 1)
	})
}

func main() {
	mux := &http.ServeMux{}
	mux.HandleFunc("/ws", onWebsocket)

	svr = nbhttp.NewServer(nbhttp.Config{
		Network:                 "tcp",
		Addrs:                   addrs,
		MaxLoad:                 1000000,
		ReleaseWebsocketPayload: true,
	}, mux, nil)

	online := int64(0)
	svr.OnOpen(func(c *nbio.Conn) {
		atomic.AddInt64(&online, 1)

	})
	svr.OnClose(func(c *nbio.Conn, err error) {
		atomic.AddInt64(&online, -1)
	})

	err := svr.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}
	defer svr.Stop()

	ticker := time.NewTicker(time.Second)
	for i := 1; true; i++ {
		<-ticker.C
		n := atomic.SwapUint64(&qps, 0)
		total += n
		_, _, s := mempool.State()
		fmt.Printf("running for %v seconds, NumGoroutine: %v, online: %v, qps: %v, total: %v\n--------------------------------\n%v\n", i, runtime.NumGoroutine(), atomic.LoadInt64(&online), n, total, s)
	}
}

var addrs = []string{
	"localhost:28001",
	"localhost:28002",
	"localhost:28003",
	"localhost:28004",
	"localhost:28005",
	"localhost:28006",
	"localhost:28007",
	"localhost:28008",
	"localhost:28009",
	"localhost:28010",

	"localhost:28011",
	"localhost:28012",
	"localhost:28013",
	"localhost:28014",
	"localhost:28015",
	"localhost:28016",
	"localhost:28017",
	"localhost:28018",
	"localhost:28019",
	"localhost:28020",

	"localhost:28021",
	"localhost:28022",
	"localhost:28023",
	"localhost:28024",
	"localhost:28025",
	"localhost:28026",
	"localhost:28027",
	"localhost:28028",
	"localhost:28029",
	"localhost:28030",

	"localhost:28031",
	"localhost:28032",
	"localhost:28033",
	"localhost:28034",
	"localhost:28035",
	"localhost:28036",
	"localhost:28037",
	"localhost:28038",
	"localhost:28039",
	"localhost:28040",

	"localhost:28041",
	"localhost:28042",
	"localhost:28043",
	"localhost:28044",
	"localhost:28045",
	"localhost:28046",
	"localhost:28047",
	"localhost:28048",
	"localhost:28049",
	"localhost:28050",
}
```

Output:
```sh
running for 8 seconds, NumGoroutine: 68, online: 20000, qps: 0, total: 20000
--------------------------------
malloc num : 60000
free num   : 60000
left times : 0

running for 9 seconds, NumGoroutine: 68, online: 0, qps: 0, total: 20000
--------------------------------
malloc num : 60000
free num   : 60000
left times : 0
```

### client
```golang
package main

import (
	"flag"
	"fmt"
	"net/url"
	"runtime"
	"sync/atomic"
	"time"

	"github.com/gorilla/websocket"
)

var (
	connected    uint64 = 0
	success      uint64 = 0
	failed       uint64 = 0
	totalSuccess uint64 = 0
	totalFailed  uint64 = 0

	online int64 = 0

	numClient    = flag.Int("c", 200000, "client num")
	numGoroutine = flag.Int("g", 500, "goroutine num")
)

func main() {
	flag.Parse()

	connNum := *numClient
	goroutineNum := *numGoroutine

	for i := 0; i < goroutineNum; i++ {
		go loop(addrs[i%len(addrs)], connNum/goroutineNum)
	}

	ticker := time.NewTicker(time.Second)
	for i := 1; true; i++ {
		<-ticker.C
		nSuccess := atomic.SwapUint64(&success, 0)
		nFailed := atomic.SwapUint64(&failed, 0)
		totalSuccess += nSuccess
		totalFailed += nFailed
		fmt.Printf("running for %v seconds, online: %v, NumGoroutine: %v, success: %v, totalSuccess: %v, failed: %v, totalFailed: %v\n", i, online, runtime.NumGoroutine(), nSuccess, totalSuccess, nFailed, totalFailed)
	}
}

func loop(addr string, connNum int) {
	u := url.URL{Scheme: "ws", Host: addr, Path: "/ws"}
	addr = u.String()

	conns := make([]*websocket.Conn, connNum)
	for i := 0; i < connNum; i++ {
		for {
			conn, _, err := websocket.DefaultDialer.Dial(addr, nil)
			if err == nil {
				conns[i] = conn
				atomic.AddUint64(&connected, 1)
				atomic.AddInt64(&online, 1)
				break
			}
			time.Sleep(time.Second / 10)
		}
	}
	for {
		for i := 0; i < connNum; i++ {
			if err := echo(conns[i]); err != nil {
				conns[i] = nil
				atomic.AddInt64(&online, -1)
			}
			// return
		}
		time.Sleep(time.Second * 10)
	}
}

func echo(c *websocket.Conn) error {
	if c == nil {
		return nil
	}
	text := "hello world"
	err := c.WriteMessage(websocket.TextMessage, []byte(text))
	if err != nil {
		fmt.Println("WriteMessage failed 111:", err)
		atomic.AddUint64(&failed, 1)
		return err
	}

	_, message, err := c.ReadMessage()
	if err != nil {
		fmt.Println("ReadMessage failed 222:", err)
		atomic.AddUint64(&failed, 1)
		return err
	}

	if string(message) != text {
		fmt.Println("ReadMessage failed 333:", string(message))
		atomic.AddUint64(&failed, 1)
	} else {
		atomic.AddUint64(&success, 1)
	}
	return nil
}

var addrs = []string{
	"localhost:28001",
	"localhost:28002",
	"localhost:28003",
	"localhost:28004",
	"localhost:28005",
	"localhost:28006",
	"localhost:28007",
	"localhost:28008",
	"localhost:28009",
	"localhost:28010",

	"localhost:28011",
	"localhost:28012",
	"localhost:28013",
	"localhost:28014",
	"localhost:28015",
	"localhost:28016",
	"localhost:28017",
	"localhost:28018",
	"localhost:28019",
	"localhost:28020",

	"localhost:28021",
	"localhost:28022",
	"localhost:28023",
	"localhost:28024",
	"localhost:28025",
	"localhost:28026",
	"localhost:28027",
	"localhost:28028",
	"localhost:28029",
	"localhost:28030",

	"localhost:28031",
	"localhost:28032",
	"localhost:28033",
	"localhost:28034",
	"localhost:28035",
	"localhost:28036",
	"localhost:28037",
	"localhost:28038",
	"localhost:28039",
	"localhost:28040",

	"localhost:28041",
	"localhost:28042",
	"localhost:28043",
	"localhost:28044",
	"localhost:28045",
	"localhost:28046",
	"localhost:28047",
	"localhost:28048",
	"localhost:28049",
	"localhost:28050",
}
```

Output:
```sh
running for 12 seconds, online: 0, NumGoroutine: 501, success: 0, totalSuccess: 20000, failed: 12042, totalFailed: 20000
```

It seems working fine.

**Comment by mehrvarz** [comment]
> So you mean it occurred when the server-side called conn.Close()?

Yes. 
 
> Full example code would be helpful.

OK. Is it correct that I only need to call conn.Close() when I want to kick out a client with a healthy connection? In all other cases, when the client disconnects itself, when the server receives OnClose, there is no need to call conn.Close(). Correct?

If this is true, then what I am saying is, that conn.Close() fails in the only situation where it is needed. Does this look right to you? Should this be enough to make a client disconnect?

```
c.wsSendMutex.Lock()
c.wsConn.WriteMessage(websocket.CloseMessage, nil)
c.wsSendMutex.Unlock()
c.wsConn.Close()
```

**Comment by mehrvarz** [comment]
> It seems working fine.

I saw this post only now. This code doesn't seem to call Close() anywhere.

**Comment by lesismal** [comment]
> c.wsSendMutex.Lock()
> c.wsConn.WriteMessage(websocket.CloseMessage, nil)
> c.wsSendMutex.Unlock()
> c.wsConn.Close()

There's no need using this `c.wsSendMutex.`

**Comment by lesismal** [comment]
> > It seems working fine.
> 
> I saw this post only now. This code doesn't seem to call Close() anywhere.
> 
> Edit: Try something like this.
> 
> ```
> func onWebsocket(w http.ResponseWriter, r *http.Request) {
> 	upgrader := websocket.NewUpgrader()
> 	conn, err := upgrader.Upgrade(w, r, nil)
> 	if err != nil {
> 		panic(err)
> 	}
> 	wsConn := conn.(*websocket.Conn)
> 	time.Sleep(1 * time.Second)
> 	wsConn.WriteMessage(websocket.CloseMessage, nil)
> 	wsConn.Close() // client should notice this
> }
> ```

Please provide the full code that can reproduce the problem.

**Comment by lesismal** [comment]
> I saw this post only now. This code doesn't seem to call Close() anywhere.

SetReadDeadline will trigger conn.Close after timeout.

**Comment by lesismal** [comment]
> func onWebsocket(w http.ResponseWriter, r *http.Request) {
> 	upgrader := websocket.NewUpgrader()
> 	conn, err := upgrader.Upgrade(w, r, nil)
> 	if err != nil {
> 		panic(err)
> 	}
> 	wsConn := conn.(*websocket.Conn)
> 	time.Sleep(1 * time.Second)
> 	wsConn.WriteMessage(websocket.CloseMessage, nil)
> 	wsConn.Close() // client should notice this
> }

And usually, you should not block(sleep) in a handler, it will block this goroutine, if many connections do like this, the goroutine pool will be slow or not available.

**Comment by lesismal** [comment]
I tried this, and also runs fine:

### server
```golang
package main

import (
	"fmt"
	"net/http"
	"runtime"
	"sync/atomic"
	"time"

	"github.com/lesismal/nbio"
	"github.com/lesismal/nbio/mempool"
	"github.com/lesismal/nbio/nbhttp"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

var (
	qps   uint64 = 0
	total uint64 = 0

	svr *nbhttp.Server
)

func onWebsocket(w http.ResponseWriter, r *http.Request) {
	upgrader := websocket.NewUpgrader()
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		panic(err)
	}
	wsConn := conn.(*websocket.Conn)
	time.AfterFunc(time.Second*5, func() {
		wsConn.WriteMessage(websocket.CloseMessage, nil)
		wsConn.Close() // client should notice this
	})
}

func main() {
	mux := &http.ServeMux{}
	mux.HandleFunc("/ws", onWebsocket)

	svr = nbhttp.NewServer(nbhttp.Config{
		Network:                 "tcp",
		Addrs:                   addrs,
		MaxLoad:                 1000000,
		ReleaseWebsocketPayload: true,
	}, mux, nil)

	online := int64(0)
	svr.OnOpen(func(c *nbio.Conn) {
		atomic.AddInt64(&online, 1)

	})
	svr.OnClose(func(c *nbio.Conn, err error) {
		atomic.AddInt64(&online, -1)
	})

	err := svr.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}
	defer svr.Stop()

	ticker := time.NewTicker(time.Second)
	for i := 1; true; i++ {
		<-ticker.C
		n := atomic.SwapUint64(&qps, 0)
		total += n
		_, _, s := mempool.State()
		fmt.Printf("running for %v seconds, NumGoroutine: %v, online: %v, qps: %v, total: %v\n--------------------------------\n%v\n", i, runtime.NumGoroutine(), atomic.LoadInt64(&online), n, total, s)
	}
}

var addrs = []string{
	"localhost:28001",
}
```

### client
```golang
package main

import (
	"flag"
	"fmt"
	"net/url"
	"runtime"
	"sync/atomic"
	"time"

	"github.com/gorilla/websocket"
)

var (
	connected    uint64 = 0
	success      uint64 = 0
	failed       uint64 = 0
	totalSuccess uint64 = 0
	totalFailed  uint64 = 0

	online int64 = 0

	numClient    = flag.Int("c", 200000, "client num")
	numGoroutine = flag.Int("g", 500, "goroutine num")
)

func main() {
	flag.Parse()

	connNum := *numClient
	goroutineNum := *numGoroutine

	for i := 0; i < goroutineNum; i++ {
		go loop(addrs[i%len(addrs)], connNum/goroutineNum)
	}

	ticker := time.NewTicker(time.Second)
	for i := 1; true; i++ {
		<-ticker.C
		nSuccess := atomic.SwapUint64(&success, 0)
		nFailed := atomic.SwapUint64(&failed, 0)
		totalSuccess += nSuccess
		totalFailed += nFailed
		fmt.Printf("running for %v seconds, online: %v, NumGoroutine: %v, success: %v, totalSuccess: %v, failed: %v, totalFailed: %v\n", i, online, runtime.NumGoroutine(), nSuccess, totalSuccess, nFailed, totalFailed)
	}
}

func loop(addr string, connNum int) {
	u := url.URL{Scheme: "ws", Host: addr, Path: "/ws"}
	addr = u.String()

	conns := make([]*websocket.Conn, connNum)
	for i := 0; i < connNum; i++ {
		for {
			conn, _, err := websocket.DefaultDialer.Dial(addr, nil)
			if err == nil {
				conns[i] = conn
				atomic.AddUint64(&connected, 1)
				atomic.AddInt64(&online, 1)
				break
			}
			time.Sleep(time.Second / 10)
		}
	}
	for {
		for i := 0; i < connNum; i++ {
			if err := echo(conns[i]); err != nil {
				conns[i] = nil
				atomic.AddInt64(&online, -1)
			}
			// return
		}
		time.Sleep(time.Second * 10)
	}
}

func echo(c *websocket.Conn) error {
	if c == nil {
		return nil
	}
	text := "hello world"
	err := c.WriteMessage(websocket.TextMessage, []byte(text))
	if err != nil {
		fmt.Println("WriteMessage failed 111:", err)
		atomic.AddUint64(&failed, 1)
		return err
	}

	_, message, err := c.ReadMessage()
	if err != nil {
		fmt.Println("ReadMessage failed 222:", err)
		atomic.AddUint64(&failed, 1)
		return err
	}

	if string(message) != text {
		fmt.Println("ReadMessage failed 333:", string(message))
		atomic.AddUint64(&failed, 1)
	} else {
		atomic.AddUint64(&success, 1)
	}
	return nil
}

var addrs = []string{
	"localhost:28001",
}
```

**Comment by lesismal** [comment]
> I tried this, and also runs fine:
> 
> ### server
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"net/http"
> 	"runtime"
> 	"sync/atomic"
> 	"time"
> 
> 	"github.com/lesismal/nbio"
> 	"github.com/lesismal/nbio/mempool"
> 	"github.com/lesismal/nbio/nbhttp"
> 	"github.com/lesismal/nbio/nbhttp/websocket"
> )
> 
> var (
> 	qps   uint64 = 0
> 	total uint64 = 0
> 
> 	svr *nbhttp.Server
> )
> 
> func onWebsocket(w http.ResponseWriter, r *http.Request) {
> 	upgrader := websocket.NewUpgrader()
> 	conn, err := upgrader.Upgrade(w, r, nil)
> 	if err != nil {
> 		panic(err)
> 	}
> 	wsConn := conn.(*websocket.Conn)
> 	time.AfterFunc(time.Second*5, func() {
> 		wsConn.WriteMessage(websocket.CloseMessage, nil)
> 		wsConn.Close() // client should notice this
> 	})
> }
> 
> func main() {
> 	mux := &http.ServeMux{}
> 	mux.HandleFunc("/ws", onWebsocket)
> 
> 	svr = nbhttp.NewServer(nbhttp.Config{
> 		Network:                 "tcp",
> 		Addrs:                   addrs,
> 		MaxLoad:                 1000000,
> 		ReleaseWebsocketPayload: true,
> 	}, mux, nil)
> 
> 	online := int64(0)
> 	svr.OnOpen(func(c *nbio.Conn) {
> 		atomic.AddInt64(&online, 1)
> 
> 	})
> 	svr.OnClose(func(c *nbio.Conn, err error) {
> 		atomic.AddInt64(&online, -1)
> 	})
> 
> 	err := svr.Start()
> 	if err != nil {
> 		fmt.Printf("nbio.Start failed: %v\n", err)
> 		return
> 	}
> 	defer svr.Stop()
> 
> 	ticker := time.NewTicker(time.Second)
> 	for i := 1; true; i++ {
> 		<-ticker.C
> 		n := atomic.SwapUint64(&qps, 0)
> 		total += n
> 		_, _, s := mempool.State()
> 		fmt.Printf("running for %v seconds, NumGoroutine: %v, online: %v, qps: %v, total: %v\n--------------------------------\n%v\n", i, runtime.NumGoroutine(), atomic.LoadInt64(&online), n, total, s)
> 	}
> }
> 
> var addrs = []string{
> 	"localhost:28001",
> }
> ```
> 
> Output:
> 
> ```shell
> running for 60 seconds, NumGoroutine: 15, online: 1000, qps: 0, total: 0
> --------------------------------
> malloc num : 3001
> free num   : 3001
> left times : 0
> 
> running for 61 seconds, NumGoroutine: 15, online: 945, qps: 0, total: 0
> --------------------------------
> malloc num : 3056
> free num   : 3056
> left times : 0
> 
> running for 62 seconds, NumGoroutine: 15, online: 0, qps: 0, total: 0
> ```
> 
> ### client
> ```go
> package main
> 
> import (
> 	"flag"
> 	"fmt"
> 	"net/url"
> 	"runtime"
> 	"sync/atomic"
> 	"time"
> 
> 	"github.com/gorilla/websocket"
> )
> 
> var (
> 	connected    uint64 = 0
> 	success      uint64 = 0
> 	failed       uint64 = 0
> 	totalSuccess uint64 = 0
> 	totalFailed  uint64 = 0
> 
> 	online int64 = 0
> 
> 	numClient    = flag.Int("c", 200000, "client num")
> 	numGoroutine = flag.Int("g", 500, "goroutine num")
> )
> 
> func main() {
> 	flag.Parse()
> 
> 	connNum := *numClient
> 	goroutineNum := *numGoroutine
> 
> 	for i := 0; i < goroutineNum; i++ {
> 		go loop(addrs[i%len(addrs)], connNum/goroutineNum)
> 	}
> 
> 	ticker := time.NewTicker(time.Second)
> 	for i := 1; true; i++ {
> 		<-ticker.C
> 		nSuccess := atomic.SwapUint64(&success, 0)
> 		nFailed := atomic.SwapUint64(&failed, 0)
> 		totalSuccess += nSuccess
> 		totalFailed += nFailed
> 		fmt.Printf("running for %v seconds, online: %v, NumGoroutine: %v, success: %v, totalSuccess: %v, failed: %v, totalFailed: %v\n", i, online, runtime.NumGoroutine(), nSuccess, totalSuccess, nFailed, totalFailed)
> 	}
> }
> 
> func loop(addr string, connNum int) {
> 	u := url.URL{Scheme: "ws", Host: addr, Path: "/ws"}
> 	addr = u.String()
> 
> 	conns := make([]*websocket.Conn, connNum)
> 	for i := 0; i < connNum; i++ {
> 		for {
> 			conn, _, err := websocket.DefaultDialer.Dial(addr, nil)
> 			if err == nil {
> 				conns[i] = conn
> 				atomic.AddUint64(&connected, 1)
> 				atomic.AddInt64(&online, 1)
> 				break
> 			}
> 			time.Sleep(time.Second / 10)
> 		}
> 	}
> 	for {
> 		for i := 0; i < connNum; i++ {
> 			if err := echo(conns[i]); err != nil {
> 				conns[i] = nil
> 				atomic.AddInt64(&online, -1)
> 			}
> 			// return
> 		}
> 		time.Sleep(time.Second * 10)
> 	}
> }
> 
> func echo(c *websocket.Conn) error {
> 	if c == nil {
> 		return nil
> 	}
> 	text := "hello world"
> 	err := c.WriteMessage(websocket.TextMessage, []byte(text))
> 	if err != nil {
> 		fmt.Println("WriteMessage failed 111:", err)
> 		atomic.AddUint64(&failed, 1)
> 		return err
> 	}
> 
> 	_, message, err := c.ReadMessage()
> 	if err != nil {
> 		fmt.Println("ReadMessage failed 222:", err)
> 		atomic.AddUint64(&failed, 1)
> 		return err
> 	}
> 
> 	if string(message) != text {
> 		fmt.Println("ReadMessage failed 333:", string(message))
> 		atomic.AddUint64(&failed, 1)
> 	} else {
> 		atomic.AddUint64(&success, 1)
> 	}
> 	return nil
> }
> 
> var addrs = []string{
> 	"localhost:28001",
> }
> ```
> 
> Output:
> 
> ```shell
> ReadMessage failed 222: websocket: close 1005 (no status)
> running for 6 seconds, online: 0, NumGoroutine: 501, success: 0, totalSuccess: 0, failed: 1000, totalFailed: 1000
> running for 7 seconds, online: 0, NumGoroutine: 501, success: 0, totalSuccess: 0, failed: 0, totalFailed: 1000
> running for 8 seconds, online: 0, NumGoroutine: 501, success: 0, totalSuccess: 0, failed: 0, totalFailed: 1000
> ```

So, please provide the full code that can reproduce the problem.

**Comment by lesismal** [comment]
I think about this problem, it may happen when the server poller read EOF before the http handler registering the wsConn.OnClose, the close event is triggered only once, so if it has been triggerd before registering the handler, the handler will not be called.

**Comment by lesismal** [comment]
> I think about this problem, it may happen when the server poller read EOF before the http handler registering the wsConn.OnClose, the close event is triggered only once, so if it has been triggerd before registering the handler, the handler will not be called.

reproduced by this example:

server:
```golang
package main

import (
	"fmt"
	"net/http"
	"runtime"
	"sync/atomic"
	"time"

	"github.com/lesismal/nbio"
	"github.com/lesismal/nbio/mempool"
	"github.com/lesismal/nbio/nbhttp"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

var (
	qps    uint64 = 0
	total  uint64 = 0
	online int64  = 0

	svr *nbhttp.Server
)

func onWebsocket(w http.ResponseWriter, r *http.Request) {
	upgrader := websocket.NewUpgrader()
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		panic(err)
	}
	wsConn := conn.(*websocket.Conn)

	// simulate that the tcp connection has been closed when registering the close handler
	time.AfterFunc(time.Second*2, func() {
		wsConn.OnClose(func(c *websocket.Conn, err error) {
			atomic.AddInt64(&online, -1)
		})
	})
}

func main() {
	mux := &http.ServeMux{}
	mux.HandleFunc("/ws", onWebsocket)

	svr = nbhttp.NewServer(nbhttp.Config{
		Network:                 "tcp",
		Addrs:                   addrs,
		MaxLoad:                 1000000,
		ReleaseWebsocketPayload: true,
	}, mux, nil)

	svr.OnOpen(func(c *nbio.Conn) {
		atomic.AddInt64(&online, 1)
	})
	svr.OnClose(func(c *nbio.Conn, err error) {

	})

	err := svr.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}
	defer svr.Stop()

	ticker := time.NewTicker(time.Second)
	for i := 1; true; i++ {
		<-ticker.C
		n := atomic.SwapUint64(&qps, 0)
		total += n
		_, _, s := mempool.State()
		fmt.Printf("running for %v seconds, NumGoroutine: %v, online: %v, qps: %v, total: %v\n--------------------------------\n%v\n", i, runtime.NumGoroutine(), atomic.LoadInt64(&online), n, total, s)
	}
}

var addrs = []string{
	"localhost:28001",
}
```

client:
```golang
package main

import (
	"net/url"

	"github.com/gorilla/websocket"
)

func main() {
	u := url.URL{Scheme: "ws", Host: "localhost:28001", Path: "/ws"}
	addr := u.String()

	c, _, err := websocket.DefaultDialer.Dial(addr, nil)
	if err != nil {
		panic(err)
	}
	c.Close()
}
```

The 4th layer's EOF is handled in poller goroutine, the 7th layer http/websocket's message is handled in another goroutine.
If the EOF comes before the registration of close handler, the close event will not be triggered again, then the close handler will be never called.

I have fixed it by this commit: https://github.com/lesismal/nbio/commit/c358bc25e055a19b393debde4445ef389e833003

I'm not sure whether this is the reason for the problem you have ever met, please try v1.1.9.

**Comment by mehrvarz** [comment]
> I have fixed it by this commit: [c358bc2](https://github.com/lesismal/nbio/commit/c358bc25e055a19b393debde4445ef389e833003)
> 
> I'm not sure whether this is the reason for the problem you have ever met, please try v1.1.9.

No, this didn't solve my issue. While working on some sample code to show you, I realized that I was having two separate issues. One was that my test client, in certain cases, didn't show errors returned by ReadMessage(). This is why I missed the disconnects, that were properly delivered by the serverside Close(). Due to this I was searching for the main issue in the wrong places. I still didn't solve my "main" issue (xxx missing out of xxxxx). But now that the test client behaves rationally, it is easy to see that it must be in my server code. So I will close this now. Apologies for the interrupt. The other guy is right: Good project. Use low memory and very fast！！！

**Comment by mehrvarz** [comment]
Really sorry to bother you again. Do you remember this post of mine?
 https://github.com/lesismal/nbio/issues/70#issuecomment-886083583
I am basically seeing the same thing again. Just less often.

I am counting how often I call wsConn.Close() and how often it returns. The two numbers should be the same, but they are not. In other words: some calls to Close() are getting stuck. In fact, the difference is exactly the number "xxx missing out of xxxxx" that I have mentioned earlier today. In my last test, that is still on my screen, 188 of 1715 calls to Close did not return.

Can you please explain why my calls to Close() got stuck before your patch? And how your patch works?
https://github.com/lesismal/llib/commit/63e6b35038526fd2ea94e3d5d23fa12908ca4476
It is not fully selfexlenatory. And pls note that I am not using the TLS server for any of this right now.

**Comment by lesismal** [comment]
> Really sorry to bother you again.

Not at all, it's my duty and I'm happy to deal with things about my repo.

> Can you please explain why my calls to Close() got stuck before your patch? And how your patch works?

There is a deadlock in the old version, because the defer Unlock()'s calling needs to wait until the end of tls.Conn.Close, then the nbio.Conn.Close [here](https://github.com/lesismal/llib/blob/master/std/crypto/tls/conn.go#L1595) would call tls.Conn.Close again, so it's deadlock. The patch code you see, Unlock is called after getting the `closed` state, no need to wait until the end of tls.Conn.Close,  then fix the deadlock.

> I am counting how often I call wsConn.Close() and how often it returns. The two numbers should be the same, but they are not. In other words: some calls to Close() are getting stuck. In fact, the difference is exactly the number "xxx missing out of xxxxx" that I have mentioned earlier today. In my last test, that is still on my screen, 188 of 1715 calls to Close did not return.

You'd better provide a full example code that can reproduce the problem, else I'm not able to know whatever happened in your project.

We can keep this issue open until we're sure it has been solved.

**Comment by lesismal** [comment]
> No, this didn't solve my issue. While working on some sample code to show you, I realized that I was having two separate issues. One was that my test client, in certain cases, didn't show errors returned by ReadMessage(). This is why I missed the disconnects, that were properly delivered by the serverside Close(). Due to this I was searching for the main issue in the wrong places. I still didn't solve my "main" issue (xxx missing out of xxxxx). But now that the test client behaves rationally, it is easy to see that it must be in my server code. So I will close this now. Apologies for the interrupt. The other guy is right: Good project. Use low memory and very fast！！！

Do you mean that nbio's http server runs fine now?
I'm glad to deal with analyzing both nbio and your client's code if you need it.

**Comment by mehrvarz** [comment]
Can you also respond to this?
> Edit: I looked at Close() in /std/crypto/tls/conn.go (the full code, not just the diff) and I think I understand what you did. If this is the std lib, how come you need to apply changes in there, to fix bugs? Did you fix your own earlier changes? Or did you change the behavior of std Close() in the TLS code? And if this is totally unrelated to the none-TLS code, then what could cause the none-TLS Close to not return in some cases? (In 188 out of 1715 cases, which are all the same?)

I noticed that Close() in std crypto/tls/conn.go looks different from yours. As if it was modified recently. It has an interesting comment in there: "If Close is called while a Write is currently in-flight...". This code is missing in your variant. Isn't it problematic to have so much deviation from the std lib?

I also looked at Close() in nbio conn_std.go. The mux in there wraps the whole method. Like in your old TLS version. I have applied the same modification to it, that you did to the TLS Close() (have the mux only frame the c.closed related code. But this did not fix my current issue. My situation is still that a low number of wsConn.Close() calls get stuck and never return.

**Comment by lesismal** [comment]
> I noticed that Close() in std crypto/tls/conn.go looks different from yours. As if it was modified recently. It has an interesting comment in there: "If Close is called while a Write is currently in-flight...". This code is missing in your variant. Isn't it problematic to have so much deviation from the std lib?

llib is not std. 
There's a mutex for read/write/close to guard the concurrency operations.
I can't explain more, because that's a long talk. As Linus said: you need to "Read The Fucking Source Code...“.

> But this did not fix my current issue. My situation is still that a low number of wsConn.Close() calls get stuck and never return.

You have not provide the full example code to reproduce your problem, if you really want to solve it, show me the code, else the more you explain, the more time we waste.

**Comment by mehrvarz** [comment]
Looks like I have it solved now. I wasn't stopping the ping deadlines correctly. Now I do :-) Thank you for your help!

**Comment by lesismal** [comment]
> Looks like I have it solved now. I wasn't stopping the ping deadlines correctly. Now I do :-) Thank you for your help!

Good job!

And this issue helps me find out https://github.com/lesismal/nbio/commit/c358bc25e055a19b393debde4445ef389e833003 and fix it, thank you very much!

**Comment by mehrvarz** [comment]
I have two leftover questions. Can you please explain your this comment of yours?

> > c.wsSendMutex.Lock()
> > c.wsConn.WriteMessage(websocket.CloseMessage, nil)
> > c.wsSendMutex.Unlock()
> > c.wsConn.Close()
> 
> There's no need using this `c.wsSendMutex.`


And a question about your "Websocket 1M Connections Example": https://github.com/lesismal/nbio/blob/e7b758dd9291cd55b752d6a3af02427ac8d49152/examples/websocket_1m/client/client.go#L58
Here you use Sleep(time.Second / 10) inside the dialer loop. Running 1M connections this way would take 27 hours while the server is doing (almost) nothing. But removing the sleep can quickly overwhelm the server, especially if TLS is being used. How would you construct a adapting client that will always "dial" as quickly as possible? Thank you.

**Comment by lesismal** [comment]
> I have two leftover questions. Can you please explain this comment of yours?

There's already a mutex in websocket.Conn, it's concurrent safe, so you do not need to use another mutex:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L201

> Here you use Sleep(time.Second / 10) inside the dialer loop. Running 1M connections this way would take 27 hours while the server is doing (almost) nothing. But removing the sleep can quickly overwhelm the server, especially if TLS is being used. How would you construct an adapting client that will always "dial" as quickly as possible? Thank you.

This is an example only because I don't have better hardware, so I need to limit some client-side code.
You can just customize the code yourself to save time.

**Comment by mehrvarz** [comment]
> There's already a mutex in websocket.Conn, it's concurrent safe, so you do not need to use another mutex:
> https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L201

Got it!

>
> This is an example only because I don't have better hardware, so I need to limit some client-side code.
> You can just customize the code yourself to save time.

But when I switch between a fast server (say, on localhost) and a slow remote server, I have to always go back and guess the best sleep duration. This is a constant hastle, especially if the speed of a target server and/or the condition of the network is unknown or even changing. Which is why I am asking you how you would construct a self-adapting dialer client. How would you go about doing that?

**Comment by mehrvarz** [comment]
This is what I am currently doing. I am starting a goroutine for every Dial(addr,nil) call, so I can start a lot of connections in parallel.

I then measure how long it takes to create each connection. The first once may get a response in under 100ms. But naturally, if you start hundreds of connections in parallel, the roundtrip time does get slower. When the roundtrip times get really slow, I slow down creation of new Dial routines. And when things get quicker, I speed up the creation of connections again.

But this approach also has it's limits. I constantly run the risk of overwhelming the server. So I add artificial delays, say, 5 ms per call to not overwhelm slow remote servers. This is much less than your 100ms, but a 5ms delay per call is limiting the top throuput to 200 connects per second. A server on localhost may be able to do much more (say, 500 cps or even more). So my question is how to do this best? For instance, I thought about creating a dedicated websocket connection for the server to be able to report back it's current condition (cpu load, request backlog, etc.). This should let me react faster to a server getting close to an overload. Faster than by measuring the roundtrip times on the client. But I have not tried this yet.

I was wondering if asking you about this would bring up some new insight. You must have thought about this very problem a lot, I am sure.

**Comment by lesismal** [comment]
> > This is what I am currently doing. I am starting a goroutine for every Dial(addr,nil) call, so I can start a lot of connections in parallel.
> > I then measure how long it takes to create each connection. The first ones may get a response in under 100ms. But naturally, if you start hundreds of connections in parallel, the roundtrip time does get slower. When the roundtrip times get really slow, I slow down creation of new Dial routines. And when things get quicker, I speed up the creation of connections again.
> > But this approach also has it's limits. I constantly run the risk of overwhelming the server. So I add artificial delays, say, 5 ms per call to not overwhelm slow remote servers. This is much less than your 100ms, but a 5ms delay per call is limiting the top throuput to 200 connects per second. A server on localhost may be able to do much more (say, 500 cps or even more). So my question is how to do this best? For instance, I thought about creating a dedicated websocket connection for the server to be able to report back it's current condition (cpu load, request backlog, etc.). This should let me react faster to a server getting close to an overload. Faster than by measuring the roundtrip times on the client. But I have not tried this yet.
> > I was wondering if asking you about this would bring up some new insight. You must have thought about this very problem a lot, I am sure.
> 
> Your client should simulate your actual business.
> 
> If what you are doing is for a load test, think about what is the designed target load capacity of your service, then simulate that.

The actual test needs to adjust different parameters. You can test according to different parameters and evaluate whether the carrying capacity of your service needs to be expanded.

**Comment by mehrvarz** [comment]
I asked a technical question. How can I make my test client run faster. I don't understand your answers, sorry.

**Comment by lesismal** [comment]
> I asked a technical question. How can I make my test client run faster. I don't understand your answers, sorry.

Do not sleep, just run your client to `fuck` the server.
If your server is overload, then make the sleep or other way that can make your client slow, and try to find a suitable sleep time.

**Comment by mehrvarz** [comment]
Your sample client runs 72+ hours. Mine finishes quicker, but my approach is still not really good. Depending on the type of server, it could finish even quicker. And it could be fully auto-adjusting. How do you write a websocket connection-simulating client, that runs as quickly as possible and adjusts itself automatically? Come on, Lesismal, help me with this one. Every user of your library will ask this question sooner or later. And then you can just provide a link to this thread :-)

**Comment by lesismal** [comment]
> Your sample client runs 72+ hours. Mine finishes quicker, but my approach is still not really good. Depending on the type of server, it could finish even quicker. And it could be fully auto-adjusting. How do you write a websocket connection-simulating client, that runs as quickly as possible and adjusts itself automatically? Come on, Lesismal, help me with this one. Every user of your library will ask this question sooner or later. And then you can just provide a link to this thread :-)

That's just an example, please customize it yourself if you need.

**Comment by mehrvarz** [comment]
> Do not sleep, just run your client to `fuck` the server.
> If your server is overload, then make the sleep or other way that can make your client slow(such as a rate Limiter), and try to find a suitable sleep time.

This is basically what I am doing now. The problem is that by the time you realize that the server is having problems, it is already too late. The server may then have a backlog of 500 or more requests. Which means that it will not recover (quickly). This means that if you had tried a little slower, you would now be faster.

We care so much about efficiency. How come this is so very inefficient? I might try the health-report back-channel idea. Any thoughts on that? If not, don't worry. I just wantet to make sure I am not wasting time with something that is already solved. Cheers

**Comment by lesismal** [comment]
> > Do not sleep, just run your client to `fuck` the server.
> > If your server is overload, then make the sleep or other way that can make your client slow(such as a rate Limiter), and try to find a suitable sleep time.
> 
> This is basically what I am doing now. The problem is that by the time you realize that the server is having problems, it is already too late. The server may then have a backlog of 500 or more requests. Which means that it will not recover (quickly). This means that if you had tried a little slower, you would now be faster.
> 
> We care so much about efficiency. How come this is so very inefficient? I might try the health-report back-channel idea. Any thoughts on that? If not, don't worry. I just wantet to make sure I am not wasting time with something that is already solved. Cheers

Different business scenarios have different levels of complexity. I cannot provide more testing on the client-side for different scenarios. Users need to perform these according to their own business needs.

**Comment by mehrvarz** [comment]
> Different business scenarios have different levels of complexity. I cannot provide more testing on the client-side for different scenarios. Users need to perform these according to their own business needs.

My question is not "business scenarios" related at all. There is no mentioning of any business specific matter anywhere.

I asked you about a connection rate limiter and optimizer. A general purpose and very technical solution. I would never ask you about some business specific solution.

**Comment by lesismal** [comment]
> That's just an example, please customize it yourself if you need.

**Comment by mehrvarz** [comment]
> You have not provide the full example code to reproduce your problem

I'm having no problems with nbio at all. Still running v1.1.9.
I just released a WebRTC telephony server making good use of it: https://github.com/mehrvarz/webcall

**Comment by lesismal** [comment]
> > You have not provide the full example code to reproduce your problem
> 
> I'm having no problems with nbio at all. Still running v1.1.9.
> I just released a WebRTC telephony server making good use of it: https://github.com/mehrvarz/webcall

Nice job!

But the latest version of nbio should be better because of some bug-fix.
